model_params:
  source_path: '/data/zhaoliang_data/aaviss-challenge1/t01_v01_s00_r03_ImageDensity/docker_output'
  model_path: 'output/dens_and_prune_20240218'
  wandb_run_name: 'dens_and_prune_20240218'
  eval: True

prune_params:
  prune_iterations: [5_000, 10_000, 15_000, 20_000]
  prune_percent: 0.6
  v_pow: 0.1
  prune_decay: 0.6

opt_params:
  iterations: 30_000
  densify_until_iter: 20_000
  densify_grad_threshold: 0.0002