model_params:
  source_path: '/data/zhaoliang_data/aaviss-challenge1/t01_v01_s00_r03_ImageDensity/docker_output'
  model_path: 'output/prune_1k_exp1'
  wandb_run_name: 'prune_1k_exp1_202402141000'
  eval: True

prune_params:
  prune_iterations: [20_000, 21_000, 22_000, 23_000, 24_000, 25_000, 26_000, 27_000, 28_000, 29_000]
  prune_percent: 0.1
  v_pow: 0.1
  prune_decay: 0.95

opt_params:
  iterations: 30_000
  densify_until_iter: 15_000