model_params:
  source_path: '/data/zhaoliang_data/aaviss-challenge1/t01_v01_s00_r03_ImageDensity/docker_output'
  model_path: 'output/prune_twice_exp2'
  wandb_run_name: 'prune_twice_exp2'
  eval: True

prune_params:
  prune_iterations: [20_000, 25_000]
  prune_percent: 0.2
  v_pow: 0.1
  prune_decay: 2.5

opt_params:
  iterations: 30_000
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0003